// 由 scripts/sync-category-lexicon.mjs 產生,不要手改。
// 來源:onion523/my-money@97f4789 的 recommendCategory(沒有歷史時,也就是只走詞庫層)在這些備註上的結果。
// 每行是「類型<Tab>備註<Tab>推薦的分類」,分類是空的代表上游沒有推薦。

enum CategoryLexiconGolden {
    static let table = """
expense	中油	汽機車輛
expense	今天中油費用	汽機車輛
expense	  中油  	汽機車輛
expense	台塑	汽機車輛
expense	今天台塑費用	汽機車輛
expense	  台塑  	汽機車輛
expense	全國加油	汽機車輛
expense	今天全國加油費用	汽機車輛
expense	  全國加油  	汽機車輛
expense	加油	汽機車輛
expense	今天加油費用	汽機車輛
expense	  加油  	汽機車輛
expense	92	汽機車輛
expense	今天92費用	汽機車輛
expense	  92  	汽機車輛
expense	95	汽機車輛
expense	今天95費用	汽機車輛
expense	  95  	汽機車輛
expense	98	汽機車輛
expense	今天98費用	汽機車輛
expense	  98  	汽機車輛
expense	柴油	汽機車輛
expense	今天柴油費用	汽機車輛
expense	  柴油  	汽機車輛
expense	機油	汽機車輛
expense	今天機油費用	汽機車輛
expense	  機油  	汽機車輛
expense	保養	汽機車輛
expense	今天保養費用	汽機車輛
expense	  保養  	汽機車輛
expense	修車	汽機車輛
expense	今天修車費用	汽機車輛
expense	  修車  	汽機車輛
expense	車貸	汽機車輛
expense	今天車貸費用	汽機車輛
expense	  車貸  	汽機車輛
expense	停車	汽機車輛
expense	今天停車費用	汽機車輛
expense	  停車  	汽機車輛
expense	停車場	汽機車輛
expense	今天停車場費用	汽機車輛
expense	  停車場  	汽機車輛
expense	停車費	汽機車輛
expense	今天停車費費用	汽機車輛
expense	  停車費  	汽機車輛
expense	嘟嘟房	汽機車輛
expense	今天嘟嘟房費用	汽機車輛
expense	  嘟嘟房  	汽機車輛
expense	udrive	汽機車輛
expense	UDRIVE	汽機車輛
expense	今天udrive費用	汽機車輛
expense	  udrive  	汽機車輛
expense	irent	汽機車輛
expense	IRENT	汽機車輛
expense	今天irent費用	汽機車輛
expense	  irent  	汽機車輛
expense	和運	汽機車輛
expense	今天和運費用	汽機車輛
expense	  和運  	汽機車輛
expense	格上	汽機車輛
expense	今天格上費用	汽機車輛
expense	  格上  	汽機車輛
expense	特斯拉	汽機車輛
expense	今天特斯拉費用	汽機車輛
expense	  特斯拉  	汽機車輛
expense	tesla	汽機車輛
expense	TESLA	汽機車輛
expense	今天tesla費用	汽機車輛
expense	  tesla  	汽機車輛
expense	gogoro	汽機車輛
expense	GOGORO	汽機車輛
expense	今天gogoro費用	汽機車輛
expense	  gogoro  	汽機車輛
expense	驗車	汽機車輛
expense	今天驗車費用	汽機車輛
expense	  驗車  	汽機車輛
expense	過路費	汽機車輛
expense	今天過路費費用	汽機車輛
expense	  過路費  	汽機車輛
expense	etc	汽機車輛
expense	ETC	汽機車輛
expense	今天etc費用	汽機車輛
expense	  etc  	汽機車輛
expense	etag	汽機車輛
expense	ETAG	汽機車輛
expense	今天etag費用	汽機車輛
expense	  etag  	汽機車輛
expense	e-tag	汽機車輛
expense	E-TAG	汽機車輛
expense	今天e-tag費用	汽機車輛
expense	  e-tag  	汽機車輛
expense	洗車	汽機車輛
expense	今天洗車費用	汽機車輛
expense	  洗車  	汽機車輛
expense	輪胎	汽機車輛
expense	今天輪胎費用	汽機車輛
expense	  輪胎  	汽機車輛
expense	鈑金	汽機車輛
expense	今天鈑金費用	汽機車輛
expense	  鈑金  	汽機車輛
expense	房租	居家水電
expense	今天房租費用	居家水電
expense	  房租  	居家水電
expense	水費	居家水電
expense	今天水費費用	居家水電
expense	  水費  	居家水電
expense	電費	居家水電
expense	今天電費費用	居家水電
expense	  電費  	居家水電
expense	台電	居家水電
expense	今天台電費用	居家水電
expense	  台電  	居家水電
expense	瓦斯	居家水電
expense	今天瓦斯費用	居家水電
expense	  瓦斯  	居家水電
expense	天然氣	居家水電
expense	今天天然氣費用	居家水電
expense	  天然氣  	居家水電
expense	管理費	居家水電
expense	今天管理費費用	居家水電
expense	  管理費  	居家水電
expense	管委會	居家水電
expense	今天管委會費用	居家水電
expense	  管委會  	居家水電
expense	社區管理	居家水電
expense	今天社區管理費用	居家水電
expense	  社區管理  	居家水電
expense	寬頻	居家水電
expense	今天寬頻費用	居家水電
expense	  寬頻  	居家水電
expense	光世代	居家水電
expense	今天光世代費用	居家水電
expense	  光世代  	居家水電
expense	第四台	居家水電
expense	今天第四台費用	居家水電
expense	  第四台  	居家水電
expense	大樓管理	居家水電
expense	今天大樓管理費用	居家水電
expense	  大樓管理  	居家水電
expense	房東	居家水電
expense	今天房東費用	居家水電
expense	  房東  	居家水電
expense	押金	居家水電
expense	今天押金費用	居家水電
expense	  押金  	居家水電
expense	netflix	數位訂閱
expense	NETFLIX	數位訂閱
expense	今天netflix費用	數位訂閱
expense	  netflix  	數位訂閱
expense	spotify	數位訂閱
expense	SPOTIFY	數位訂閱
expense	今天spotify費用	數位訂閱
expense	  spotify  	數位訂閱
expense	chatgpt	數位訂閱
expense	CHATGPT	數位訂閱
expense	今天chatgpt費用	數位訂閱
expense	  chatgpt  	數位訂閱
expense	openai	數位訂閱
expense	OPENAI	數位訂閱
expense	今天openai費用	數位訂閱
expense	  openai  	數位訂閱
expense	youtube	數位訂閱
expense	YOUTUBE	數位訂閱
expense	今天youtube費用	數位訂閱
expense	  youtube  	數位訂閱
expense	premium	數位訂閱
expense	PREMIUM	數位訂閱
expense	今天premium費用	數位訂閱
expense	  premium  	數位訂閱
expense	disney	數位訂閱
expense	DISNEY	數位訂閱
expense	今天disney費用	數位訂閱
expense	  disney  	數位訂閱
expense	icloud	數位訂閱
expense	ICLOUD	數位訂閱
expense	今天icloud費用	數位訂閱
expense	  icloud  	數位訂閱
expense	google one	數位訂閱
expense	GOOGLE ONE	數位訂閱
expense	今天google one費用	數位訂閱
expense	  google one  	數位訂閱
expense	apple one	數位訂閱
expense	APPLE ONE	數位訂閱
expense	今天apple one費用	數位訂閱
expense	  apple one  	數位訂閱
expense	apple music	數位訂閱
expense	APPLE MUSIC	數位訂閱
expense	今天apple music費用	數位訂閱
expense	  apple music  	數位訂閱
expense	github	數位訂閱
expense	GITHUB	數位訂閱
expense	今天github費用	數位訂閱
expense	  github  	數位訂閱
expense	cursor	數位訂閱
expense	CURSOR	數位訂閱
expense	今天cursor費用	數位訂閱
expense	  cursor  	數位訂閱
expense	midjourney	數位訂閱
expense	MIDJOURNEY	數位訂閱
expense	今天midjourney費用	數位訂閱
expense	  midjourney  	數位訂閱
expense	notion	數位訂閱
expense	NOTION	數位訂閱
expense	今天notion費用	數位訂閱
expense	  notion  	數位訂閱
expense	kkbox	數位訂閱
expense	KKBOX	數位訂閱
expense	今天kkbox費用	數位訂閱
expense	  kkbox  	數位訂閱
expense	line music	數位訂閱
expense	LINE MUSIC	數位訂閱
expense	今天line music費用	數位訂閱
expense	  line music  	數位訂閱
expense	電信費	數位訂閱
expense	今天電信費費用	數位訂閱
expense	  電信費  	數位訂閱
expense	遠傳	數位訂閱
expense	今天遠傳費用	數位訂閱
expense	  遠傳  	數位訂閱
expense	台灣大哥大	數位訂閱
expense	今天台灣大哥大費用	數位訂閱
expense	  台灣大哥大  	數位訂閱
expense	中華電信	數位訂閱
expense	今天中華電信費用	數位訂閱
expense	  中華電信  	數位訂閱
expense	門號	數位訂閱
expense	今天門號費用	數位訂閱
expense	  門號  	數位訂閱
expense	月租	數位訂閱
expense	今天月租費用	數位訂閱
expense	  月租  	數位訂閱
expense	剪髮	美妝保養
expense	今天剪髮費用	美妝保養
expense	  剪髮  	美妝保養
expense	理髮	美妝保養
expense	今天理髮費用	美妝保養
expense	  理髮  	美妝保養
expense	剪頭	美妝保養
expense	今天剪頭費用	美妝保養
expense	  剪頭  	美妝保養
expense	頭髮	美妝保養
expense	今天頭髮費用	美妝保養
expense	  頭髮  	美妝保養
expense	染髮	美妝保養
expense	今天染髮費用	美妝保養
expense	  染髮  	美妝保養
expense	燙髮	美妝保養
expense	今天燙髮費用	美妝保養
expense	  燙髮  	美妝保養
expense	美甲	美妝保養
expense	今天美甲費用	美妝保養
expense	  美甲  	美妝保養
expense	美睫	美妝保養
expense	今天美睫費用	美妝保養
expense	  美睫  	美妝保養
expense	做臉	美妝保養
expense	今天做臉費用	美妝保養
expense	  做臉  	美妝保養
expense	護膚	美妝保養
expense	今天護膚費用	美妝保養
expense	  護膚  	美妝保養
expense	spa	美妝保養
expense	SPA	美妝保養
expense	今天spa費用	美妝保養
expense	  spa  	美妝保養
expense	彩妝	美妝保養
expense	今天彩妝費用	美妝保養
expense	  彩妝  	美妝保養
expense	化妝品	美妝保養
expense	今天化妝品費用	美妝保養
expense	  化妝品  	美妝保養
expense	口紅	美妝保養
expense	今天口紅費用	美妝保養
expense	  口紅  	美妝保養
expense	粉底	美妝保養
expense	今天粉底費用	美妝保養
expense	  粉底  	美妝保養
expense	精華液	美妝保養
expense	今天精華液費用	美妝保養
expense	  精華液  	美妝保養
expense	面膜	美妝保養
expense	今天面膜費用	美妝保養
expense	  面膜  	美妝保養
expense	醫美	美妝保養
expense	今天醫美費用	美妝保養
expense	  醫美  	美妝保養
expense	雷射	美妝保養
expense	今天雷射費用	美妝保養
expense	  雷射  	美妝保養
expense	sk-ii	美妝保養
expense	SK-II	美妝保養
expense	今天sk-ii費用	美妝保養
expense	  sk-ii  	美妝保養
expense	雅詩蘭黛	美妝保養
expense	今天雅詩蘭黛費用	美妝保養
expense	  雅詩蘭黛  	美妝保養
expense	蘭蔻	美妝保養
expense	今天蘭蔻費用	美妝保養
expense	  蘭蔻  	美妝保養
expense	植村秀	美妝保養
expense	今天植村秀費用	美妝保養
expense	  植村秀  	美妝保養
expense	理膚寶水	美妝保養
expense	今天理膚寶水費用	居家水電
expense	  理膚寶水  	美妝保養
expense	貓砂	寵物毛孩
expense	今天貓砂費用	寵物毛孩
expense	  貓砂  	寵物毛孩
expense	飼料	寵物毛孩
expense	今天飼料費用	寵物毛孩
expense	  飼料  	寵物毛孩
expense	罐頭	寵物毛孩
expense	今天罐頭費用	寵物毛孩
expense	  罐頭  	寵物毛孩
expense	主食罐	寵物毛孩
expense	今天主食罐費用	寵物毛孩
expense	  主食罐  	寵物毛孩
expense	副食罐	寵物毛孩
expense	今天副食罐費用	寵物毛孩
expense	  副食罐  	寵物毛孩
expense	肉泥	寵物毛孩
expense	今天肉泥費用	寵物毛孩
expense	  肉泥  	寵物毛孩
expense	化毛膏	寵物毛孩
expense	今天化毛膏費用	寵物毛孩
expense	  化毛膏  	寵物毛孩
expense	貓草	寵物毛孩
expense	今天貓草費用	寵物毛孩
expense	  貓草  	寵物毛孩
expense	獸醫	寵物毛孩
expense	今天獸醫費用	寵物毛孩
expense	  獸醫  	寵物毛孩
expense	動物醫院	寵物毛孩
expense	今天動物醫院費用	寵物毛孩
expense	  動物醫院  	寵物毛孩
expense	寵物看診	寵物毛孩
expense	今天寵物看診費用	寵物毛孩
expense	  寵物看診  	寵物毛孩
expense	狂犬病	寵物毛孩
expense	今天狂犬病費用	寵物毛孩
expense	  狂犬病  	寵物毛孩
expense	驅蟲	寵物毛孩
expense	今天驅蟲費用	寵物毛孩
expense	  驅蟲  	寵物毛孩
expense	寵物美容	寵物毛孩
expense	今天寵物美容費用	寵物毛孩
expense	  寵物美容  	寵物毛孩
expense	結紮	寵物毛孩
expense	今天結紮費用	寵物毛孩
expense	  結紮  	寵物毛孩
expense	貓抓板	寵物毛孩
expense	今天貓抓板費用	寵物毛孩
expense	  貓抓板  	寵物毛孩
expense	汪喵星球	寵物毛孩
expense	今天汪喵星球費用	寵物毛孩
expense	  汪喵星球  	寵物毛孩
expense	怪獸部落	寵物毛孩
expense	今天怪獸部落費用	寵物毛孩
expense	  怪獸部落  	寵物毛孩
expense	毛孩	寵物毛孩
expense	今天毛孩費用	寵物毛孩
expense	  毛孩  	寵物毛孩
expense	寵物公園	寵物毛孩
expense	今天寵物公園費用	寵物毛孩
expense	  寵物公園  	寵物毛孩
expense	機票	旅行度假
expense	今天機票費用	旅行度假
expense	  機票  	旅行度假
expense	長榮	旅行度假
expense	今天長榮費用	旅行度假
expense	  長榮  	旅行度假
expense	華航	旅行度假
expense	今天華航費用	旅行度假
expense	  華航  	旅行度假
expense	星宇	旅行度假
expense	今天星宇費用	旅行度假
expense	  星宇  	旅行度假
expense	虎航	旅行度假
expense	今天虎航費用	旅行度假
expense	  虎航  	旅行度假
expense	airbnb	旅行度假
expense	AIRBNB	旅行度假
expense	今天airbnb費用	旅行度假
expense	  airbnb  	旅行度假
expense	agoda	旅行度假
expense	AGODA	旅行度假
expense	今天agoda費用	旅行度假
expense	  agoda  	旅行度假
expense	booking	旅行度假
expense	BOOKING	旅行度假
expense	今天booking費用	旅行度假
expense	  booking  	旅行度假
expense	飯店	旅行度假
expense	今天飯店費用	旅行度假
expense	  飯店  	旅行度假
expense	民宿	旅行度假
expense	今天民宿費用	旅行度假
expense	  民宿  	旅行度假
expense	渡假	旅行度假
expense	今天渡假費用	旅行度假
expense	  渡假  	旅行度假
expense	度假	旅行度假
expense	今天度假費用	旅行度假
expense	  度假  	旅行度假
expense	旅館	旅行度假
expense	今天旅館費用	旅行度假
expense	  旅館  	旅行度假
expense	青年旅館	旅行度假
expense	今天青年旅館費用	旅行度假
expense	  青年旅館  	旅行度假
expense	包棟	旅行度假
expense	今天包棟費用	旅行度假
expense	  包棟  	旅行度假
expense	出國	旅行度假
expense	今天出國費用	旅行度假
expense	  出國  	旅行度假
expense	伴手禮	旅行度假
expense	今天伴手禮費用	旅行度假
expense	  伴手禮  	旅行度假
expense	景點門票	旅行度假
expense	今天景點門票費用	旅行度假
expense	  景點門票  	旅行度假
expense	迪士尼	旅行度假
expense	今天迪士尼費用	旅行度假
expense	  迪士尼  	旅行度假
expense	環球影城	旅行度假
expense	今天環球影城費用	旅行度假
expense	  環球影城  	旅行度假
expense	klook	旅行度假
expense	KLOOK	旅行度假
expense	今天klook費用	旅行度假
expense	  klook  	旅行度假
expense	kkday	旅行度假
expense	KKDAY	旅行度假
expense	今天kkday費用	旅行度假
expense	  kkday  	旅行度假
expense	喜酒	社交人情
expense	今天喜酒費用	社交人情
expense	  喜酒  	社交人情
expense	紅包	社交人情
expense	今天紅包費用	社交人情
expense	  紅包  	社交人情
expense	白包	社交人情
expense	今天白包費用	社交人情
expense	  白包  	社交人情
expense	奠儀	社交人情
expense	今天奠儀費用	社交人情
expense	  奠儀  	社交人情
expense	禮金	社交人情
expense	今天禮金費用	社交人情
expense	  禮金  	社交人情
expense	彌月	社交人情
expense	今天彌月費用	社交人情
expense	  彌月  	社交人情
expense	滿月	社交人情
expense	今天滿月費用	社交人情
expense	  滿月  	社交人情
expense	過年紅包	社交人情
expense	今天過年紅包費用	社交人情
expense	  過年紅包  	社交人情
expense	壓歲錢	社交人情
expense	今天壓歲錢費用	社交人情
expense	  壓歲錢  	社交人情
expense	送禮	社交人情
expense	今天送禮費用	社交人情
expense	  送禮  	社交人情
expense	禮盒	社交人情
expense	今天禮盒費用	社交人情
expense	  禮盒  	社交人情
expense	請客	社交人情
expense	今天請客費用	社交人情
expense	  請客  	社交人情
expense	聚餐費	社交人情
expense	今天聚餐費費用	社交人情
expense	  聚餐費  	社交人情
expense	交際	社交人情
expense	今天交際費用	社交人情
expense	  交際  	社交人情
expense	應酬	社交人情
expense	今天應酬費用	社交人情
expense	  應酬  	社交人情
expense	保費	保險稅費
expense	今天保費費用	保險稅費
expense	  保費  	保險稅費
expense	保險	保險稅費
expense	今天保險費用	保險稅費
expense	  保險  	保險稅費
expense	南山	保險稅費
expense	今天南山費用	保險稅費
expense	  南山  	保險稅費
expense	國泰人壽	保險稅費
expense	今天國泰人壽費用	保險稅費
expense	  國泰人壽  	保險稅費
expense	富邦人壽	保險稅費
expense	今天富邦人壽費用	保險稅費
expense	  富邦人壽  	保險稅費
expense	新光人壽	保險稅費
expense	今天新光人壽費用	保險稅費
expense	  新光人壽  	保險稅費
expense	台灣人壽	保險稅費
expense	今天台灣人壽費用	保險稅費
expense	  台灣人壽  	保險稅費
expense	三商美邦	保險稅費
expense	今天三商美邦費用	保險稅費
expense	  三商美邦  	保險稅費
expense	醫療險	保險稅費
expense	今天醫療險費用	保險稅費
expense	  醫療險  	保險稅費
expense	意外險	保險稅費
expense	今天意外險費用	保險稅費
expense	  意外險  	保險稅費
expense	儲蓄險	保險稅費
expense	今天儲蓄險費用	保險稅費
expense	  儲蓄險  	保險稅費
expense	車險	保險稅費
expense	今天車險費用	保險稅費
expense	  車險  	保險稅費
expense	強制險	保險稅費
expense	今天強制險費用	保險稅費
expense	  強制險  	保險稅費
expense	第三責任險	保險稅費
expense	今天第三責任險費用	保險稅費
expense	  第三責任險  	保險稅費
expense	所得稅	保險稅費
expense	今天所得稅費用	保險稅費
expense	  所得稅  	保險稅費
expense	綜所稅	保險稅費
expense	今天綜所稅費用	保險稅費
expense	  綜所稅  	保險稅費
expense	房屋稅	保險稅費
expense	今天房屋稅費用	保險稅費
expense	  房屋稅  	保險稅費
expense	地價稅	保險稅費
expense	今天地價稅費用	保險稅費
expense	  地價稅  	保險稅費
expense	牌照稅	保險稅費
expense	今天牌照稅費用	保險稅費
expense	  牌照稅  	保險稅費
expense	燃料費	保險稅費
expense	今天燃料費費用	保險稅費
expense	  燃料費  	保險稅費
expense	飯	餐飲
expense	今天飯費用	餐飲
expense	  飯  	餐飲
expense	麵	餐飲
expense	今天麵費用	餐飲
expense	  麵  	餐飲
expense	餐	餐飲
expense	今天餐費用	餐飲
expense	  餐  	餐飲
expense	吃	餐飲
expense	今天吃費用	餐飲
expense	  吃  	餐飲
expense	喝	餐飲
expense	今天喝費用	餐飲
expense	  喝  	餐飲
expense	早	餐飲
expense	今天早費用	餐飲
expense	  早  	餐飲
expense	午	餐飲
expense	今天午費用	餐飲
expense	  午  	餐飲
expense	晚	餐飲
expense	今天晚費用	餐飲
expense	  晚  	餐飲
expense	宵夜	餐飲
expense	今天宵夜費用	餐飲
expense	  宵夜  	餐飲
expense	咖啡	餐飲
expense	今天咖啡費用	餐飲
expense	  咖啡  	餐飲
expense	茶	餐飲
expense	今天茶費用	餐飲
expense	  茶  	餐飲
expense	飲料	餐飲
expense	今天飲料費用	餐飲
expense	  飲料  	餐飲
expense	麥當勞	餐飲
expense	今天麥當勞費用	餐飲
expense	  麥當勞  	餐飲
expense	肯德基	餐飲
expense	今天肯德基費用	餐飲
expense	  肯德基  	餐飲
expense	摩斯	餐飲
expense	今天摩斯費用	餐飲
expense	  摩斯  	餐飲
expense	星巴克	餐飲
expense	今天星巴克費用	餐飲
expense	  星巴克  	餐飲
expense	壽司	餐飲
expense	今天壽司費用	餐飲
expense	  壽司  	餐飲
expense	爭鮮	餐飲
expense	今天爭鮮費用	餐飲
expense	  爭鮮  	餐飲
expense	拉麵	餐飲
expense	今天拉麵費用	餐飲
expense	  拉麵  	餐飲
expense	便當	餐飲
expense	今天便當費用	餐飲
expense	  便當  	餐飲
expense	火鍋	餐飲
expense	今天火鍋費用	餐飲
expense	  火鍋  	餐飲
expense	餐廳	餐飲
expense	今天餐廳費用	餐飲
expense	  餐廳  	餐飲
expense	披薩	餐飲
expense	今天披薩費用	餐飲
expense	  披薩  	餐飲
expense	全家	餐飲
expense	今天全家費用	餐飲
expense	  全家  	餐飲
expense	7-11	餐飲
expense	今天7-11費用	餐飲
expense	  7-11  	餐飲
expense	小七	餐飲
expense	今天小七費用	餐飲
expense	  小七  	餐飲
expense	路易莎	餐飲
expense	今天路易莎費用	餐飲
expense	  路易莎  	餐飲
expense	麻古	餐飲
expense	今天麻古費用	餐飲
expense	  麻古  	餐飲
expense	迷客夏	餐飲
expense	今天迷客夏費用	餐飲
expense	  迷客夏  	餐飲
expense	五十嵐	餐飲
expense	今天五十嵐費用	餐飲
expense	  五十嵐  	餐飲
expense	50嵐	餐飲
expense	今天50嵐費用	餐飲
expense	  50嵐  	餐飲
expense	清心	餐飲
expense	今天清心費用	餐飲
expense	  清心  	餐飲
expense	可不可	餐飲
expense	今天可不可費用	餐飲
expense	  可不可  	餐飲
expense	外送	餐飲
expense	今天外送費用	餐飲
expense	  外送  	餐飲
expense	ubereats	餐飲
expense	UBEREATS	餐飲
expense	今天ubereats費用	餐飲
expense	  ubereats  	餐飲
expense	foodpanda	餐飲
expense	FOODPANDA	餐飲
expense	今天foodpanda費用	餐飲
expense	  foodpanda  	餐飲
expense	下午茶	餐飲
expense	今天下午茶費用	餐飲
expense	  下午茶  	餐飲
expense	點心	餐飲
expense	今天點心費用	餐飲
expense	  點心  	餐飲
expense	麵包	餐飲
expense	今天麵包費用	餐飲
expense	  麵包  	餐飲
expense	烘焙	餐飲
expense	今天烘焙費用	餐飲
expense	  烘焙  	餐飲
expense	捷運	交通
expense	今天捷運費用	交通
expense	  捷運  	交通
expense	公車	交通
expense	今天公車費用	交通
expense	  公車  	交通
expense	高鐵	交通
expense	今天高鐵費用	交通
expense	  高鐵  	交通
expense	台鐵	交通
expense	今天台鐵費用	交通
expense	  台鐵  	交通
expense	火車	交通
expense	今天火車費用	交通
expense	  火車  	交通
expense	悠遊卡	交通
expense	今天悠遊卡費用	交通
expense	  悠遊卡  	交通
expense	一卡通	交通
expense	今天一卡通費用	交通
expense	  一卡通  	交通
expense	icash	交通
expense	ICASH	交通
expense	今天icash費用	交通
expense	  icash  	交通
expense	uber	交通
expense	UBER	交通
expense	今天uber費用	交通
expense	  uber  	交通
expense	計程車	交通
expense	今天計程車費用	交通
expense	  計程車  	交通
expense	小黃	交通
expense	今天小黃費用	交通
expense	  小黃  	交通
expense	大都會	交通
expense	今天大都會費用	交通
expense	  大都會  	交通
expense	55688	交通
expense	今天55688費用	交通
expense	  55688  	交通
expense	客運	交通
expense	今天客運費用	交通
expense	  客運  	交通
expense	國光	交通
expense	今天國光費用	交通
expense	  國光  	交通
expense	統聯	交通
expense	今天統聯費用	交通
expense	  統聯  	交通
expense	渡輪	交通
expense	今天渡輪費用	交通
expense	  渡輪  	交通
expense	纜車	交通
expense	今天纜車費用	交通
expense	  纜車  	交通
expense	遊戲	娛樂
expense	今天遊戲費用	娛樂
expense	  遊戲  	娛樂
expense	switch	娛樂
expense	SWITCH	娛樂
expense	今天switch費用	娛樂
expense	  switch  	娛樂
expense	ps5	娛樂
expense	PS5	娛樂
expense	今天ps5費用	娛樂
expense	  ps5  	娛樂
expense	xbox	娛樂
expense	XBOX	娛樂
expense	今天xbox費用	娛樂
expense	  xbox  	娛樂
expense	steam	娛樂
expense	STEAM	娛樂
expense	今天steam費用	娛樂
expense	  steam  	娛樂
expense	電影	娛樂
expense	今天電影費用	娛樂
expense	  電影  	娛樂
expense	威秀	娛樂
expense	今天威秀費用	娛樂
expense	  威秀  	娛樂
expense	國賓	娛樂
expense	今天國賓費用	娛樂
expense	  國賓  	娛樂
expense	秀泰	娛樂
expense	今天秀泰費用	娛樂
expense	  秀泰  	娛樂
expense	ktv	娛樂
expense	KTV	娛樂
expense	今天ktv費用	娛樂
expense	  ktv  	娛樂
expense	錢櫃	娛樂
expense	今天錢櫃費用	娛樂
expense	  錢櫃  	娛樂
expense	好樂迪	娛樂
expense	今天好樂迪費用	娛樂
expense	  好樂迪  	娛樂
expense	唱歌	娛樂
expense	今天唱歌費用	娛樂
expense	  唱歌  	娛樂
expense	展覽	娛樂
expense	今天展覽費用	娛樂
expense	  展覽  	娛樂
expense	演唱會	娛樂
expense	今天演唱會費用	娛樂
expense	  演唱會  	娛樂
expense	門票	娛樂
expense	今天門票費用	娛樂
expense	  門票  	娛樂
expense	扭蛋	娛樂
expense	今天扭蛋費用	娛樂
expense	  扭蛋  	娛樂
expense	動漫	娛樂
expense	今天動漫費用	娛樂
expense	  動漫  	娛樂
expense	桌遊	娛樂
expense	今天桌遊費用	娛樂
expense	  桌遊  	娛樂
expense	露營	娛樂
expense	今天露營費用	娛樂
expense	  露營  	娛樂
expense	公仔	娛樂
expense	今天公仔費用	娛樂
expense	  公仔  	娛樂
expense	診所	醫療
expense	今天診所費用	醫療
expense	  診所  	醫療
expense	醫院	醫療
expense	今天醫院費用	醫療
expense	  醫院  	醫療
expense	看病	醫療
expense	今天看病費用	醫療
expense	  看病  	醫療
expense	掛號	醫療
expense	今天掛號費用	醫療
expense	  掛號  	醫療
expense	牙醫	醫療
expense	今天牙醫費用	醫療
expense	  牙醫  	醫療
expense	眼科	醫療
expense	今天眼科費用	醫療
expense	  眼科  	醫療
expense	耳鼻喉	醫療
expense	今天耳鼻喉費用	醫療
expense	  耳鼻喉  	醫療
expense	皮膚科	醫療
expense	今天皮膚科費用	醫療
expense	  皮膚科  	醫療
expense	健保	醫療
expense	今天健保費用	保險稅費
expense	  健保  	醫療
expense	感冒	醫療
expense	今天感冒費用	醫療
expense	  感冒  	醫療
expense	藥局	醫療
expense	今天藥局費用	醫療
expense	  藥局  	醫療
expense	大樹藥局	醫療
expense	今天大樹藥局費用	醫療
expense	  大樹藥局  	醫療
expense	丁丁藥局	醫療
expense	今天丁丁藥局費用	醫療
expense	  丁丁藥局  	醫療
expense	屈臣氏藥妝	醫療
expense	今天屈臣氏藥妝費用	醫療
expense	  屈臣氏藥妝  	醫療
expense	康是美藥品	醫療
expense	今天康是美藥品費用	醫療
expense	  康是美藥品  	醫療
expense	保健食品	醫療
expense	今天保健食品費用	醫療
expense	  保健食品  	醫療
expense	維他命	醫療
expense	今天維他命費用	醫療
expense	  維他命  	醫療
expense	益生菌	醫療
expense	今天益生菌費用	醫療
expense	  益生菌  	醫療
expense	疫苗	醫療
expense	今天疫苗費用	醫療
expense	  疫苗  	醫療
expense	復健	醫療
expense	今天復健費用	醫療
expense	  復健  	醫療
expense	書	教育
expense	今天書費用	教育
expense	  書  	教育
expense	書店	教育
expense	今天書店費用	教育
expense	  書店  	教育
expense	誠品	教育
expense	今天誠品費用	教育
expense	  誠品  	教育
expense	博客來	教育
expense	今天博客來費用	教育
expense	  博客來  	教育
expense	線上課程	教育
expense	今天線上課程費用	教育
expense	  線上課程  	教育
expense	hahow	教育
expense	HAHOW	教育
expense	今天hahow費用	教育
expense	  hahow  	教育
expense	udemy	教育
expense	UDEMY	教育
expense	今天udemy費用	教育
expense	  udemy  	教育
expense	學費	教育
expense	今天學費費用	教育
expense	  學費  	教育
expense	補習	教育
expense	今天補習費用	教育
expense	  補習  	教育
expense	補習班	教育
expense	今天補習班費用	教育
expense	  補習班  	教育
expense	文具	教育
expense	今天文具費用	教育
expense	  文具  	教育
expense	筆記本	教育
expense	今天筆記本費用	教育
expense	  筆記本  	教育
expense	考試	教育
expense	今天考試費用	教育
expense	  考試  	教育
expense	考照	教育
expense	今天考照費用	教育
expense	  考照  	教育
expense	多益	教育
expense	今天多益費用	教育
expense	  多益  	教育
expense	教材	教育
expense	今天教材費用	教育
expense	  教材  	教育
expense	買	購物
expense	今天買費用	購物
expense	  買  	購物
expense	衣服	購物
expense	今天衣服費用	購物
expense	  衣服  	購物
expense	服飾	購物
expense	今天服飾費用	購物
expense	  服飾  	購物
expense	鞋	購物
expense	今天鞋費用	購物
expense	  鞋  	購物
expense	包	購物
expense	今天包費用	購物
expense	  包  	購物
expense	uniqlo	購物
expense	UNIQLO	購物
expense	今天uniqlo費用	購物
expense	  uniqlo  	購物
expense	net	購物
expense	NET	購物
expense	今天net費用	購物
expense	  net  	購物
expense	zara	購物
expense	ZARA	購物
expense	今天zara費用	購物
expense	  zara  	購物
expense	h&m	購物
expense	H&M	購物
expense	今天h&m費用	購物
expense	  h&m  	購物
expense	gu	購物
expense	GU	購物
expense	今天gu費用	購物
expense	  gu  	購物
expense	網購	購物
expense	今天網購費用	購物
expense	  網購  	購物
expense	蝦皮	購物
expense	今天蝦皮費用	購物
expense	  蝦皮  	購物
expense	momo	購物
expense	MOMO	購物
expense	今天momo費用	購物
expense	  momo  	購物
expense	pchome	購物
expense	PCHOME	購物
expense	今天pchome費用	購物
expense	  pchome  	購物
expense	淘寶	購物
expense	今天淘寶費用	購物
expense	  淘寶  	購物
expense	amazon	購物
expense	AMAZON	購物
expense	今天amazon費用	購物
expense	  amazon  	購物
expense	好市多	購物
expense	今天好市多費用	購物
expense	  好市多  	購物
expense	costco	購物
expense	COSTCO	購物
expense	今天costco費用	購物
expense	  costco  	購物
expense	無印良品	購物
expense	今天無印良品費用	購物
expense	  無印良品  	購物
expense	muji	購物
expense	MUJI	購物
expense	今天muji費用	購物
expense	  muji  	購物
expense	宜得利	購物
expense	今天宜得利費用	購物
expense	  宜得利  	購物
expense	nitori	購物
expense	NITORI	購物
expense	今天nitori費用	購物
expense	  nitori  	購物
expense	飾品	購物
expense	今天飾品費用	購物
expense	  飾品  	購物
expense	手錶	購物
expense	今天手錶費用	購物
expense	  手錶  	購物
expense	3c	購物
expense	3C	購物
expense	今天3c費用	購物
expense	  3c  	購物
expense	筆電	購物
expense	今天筆電費用	居家水電
expense	  筆電  	購物
expense	手機	購物
expense	今天手機費用	購物
expense	  手機  	購物
expense	ipad	購物
expense	IPAD	購物
expense	今天ipad費用	購物
expense	  ipad  	購物
expense	iphone	購物
expense	IPHONE	購物
expense	今天iphone費用	購物
expense	  iphone  	購物
expense	鍵盤	購物
expense	今天鍵盤費用	購物
expense	  鍵盤  	購物
expense	耳機	購物
expense	今天耳機費用	購物
expense	  耳機  	購物
expense	日常	生活
expense	今天日常費用	生活
expense	  日常  	生活
expense	生活	生活
expense	今天生活費用	生活
expense	  生活  	生活
expense	超市	生活
expense	今天超市費用	生活
expense	  超市  	生活
expense	全聯	生活
expense	今天全聯費用	生活
expense	  全聯  	生活
expense	家樂福	生活
expense	今天家樂福費用	生活
expense	  家樂福  	生活
expense	大潤發	生活
expense	今天大潤發費用	生活
expense	  大潤發  	生活
expense	愛買	購物
expense	今天愛買費用	購物
expense	  愛買  	購物
expense	屈臣氏	生活
expense	今天屈臣氏費用	生活
expense	  屈臣氏  	生活
expense	康是美	生活
expense	今天康是美費用	生活
expense	  康是美  	生活
expense	寶雅	生活
expense	今天寶雅費用	生活
expense	  寶雅  	生活
expense	ikea	生活
expense	IKEA	生活
expense	今天ikea費用	生活
expense	  ikea  	生活
expense	特力屋	生活
expense	今天特力屋費用	生活
expense	  特力屋  	生活
expense	小北百貨	生活
expense	今天小北百貨費用	生活
expense	  小北百貨  	生活
expense	水電行	生活
expense	今天水電行費用	生活
expense	  水電行  	生活
expense	五金	生活
expense	今天五金費用	生活
expense	  五金  	生活
expense	燈泡	生活
expense	今天燈泡費用	生活
expense	  燈泡  	生活
expense	電池	生活
expense	今天電池費用	生活
expense	  電池  	生活
expense	洗髮精	生活
expense	今天洗髮精費用	生活
expense	  洗髮精  	生活
expense	沐浴乳	生活
expense	今天沐浴乳費用	生活
expense	  沐浴乳  	生活
expense	洗衣精	生活
expense	今天洗衣精費用	生活
expense	  洗衣精  	生活
expense	洗碗精	生活
expense	今天洗碗精費用	生活
expense	  洗碗精  	生活
expense	抹布	生活
expense	今天抹布費用	生活
expense	  抹布  	生活
expense	垃圾袋	生活
expense	今天垃圾袋費用	生活
expense	  垃圾袋  	生活
expense	打掃	生活
expense	今天打掃費用	生活
expense	  打掃  	生活
expense	中油房租	汽機車輛
expense	中油netflix	汽機車輛
expense	中油剪髮	汽機車輛
expense	中油貓砂	汽機車輛
expense	中油機票	汽機車輛
expense	中油喜酒	汽機車輛
expense	中油保費	汽機車輛
expense	中油飯	汽機車輛
expense	中油捷運	汽機車輛
expense	中油遊戲	汽機車輛
expense	中油診所	汽機車輛
expense	中油書	汽機車輛
expense	中油買	汽機車輛
expense	中油日常	汽機車輛
expense	房租中油	汽機車輛
expense	房租netflix	居家水電
expense	房租剪髮	居家水電
expense	房租貓砂	居家水電
expense	房租機票	居家水電
expense	房租喜酒	居家水電
expense	房租保費	居家水電
expense	房租飯	居家水電
expense	房租捷運	居家水電
expense	房租遊戲	居家水電
expense	房租診所	居家水電
expense	房租書	居家水電
expense	房租買	居家水電
expense	房租日常	居家水電
expense	netflix中油	汽機車輛
expense	netflix房租	居家水電
expense	netflix剪髮	數位訂閱
expense	netflix貓砂	數位訂閱
expense	netflix機票	數位訂閱
expense	netflix喜酒	數位訂閱
expense	netflix保費	數位訂閱
expense	netflix飯	數位訂閱
expense	netflix捷運	數位訂閱
expense	netflix遊戲	數位訂閱
expense	netflix診所	數位訂閱
expense	netflix書	數位訂閱
expense	netflix買	數位訂閱
expense	netflix日常	數位訂閱
expense	剪髮中油	汽機車輛
expense	剪髮房租	居家水電
expense	剪髮netflix	數位訂閱
expense	剪髮貓砂	美妝保養
expense	剪髮機票	美妝保養
expense	剪髮喜酒	美妝保養
expense	剪髮保費	美妝保養
expense	剪髮飯	美妝保養
expense	剪髮捷運	美妝保養
expense	剪髮遊戲	美妝保養
expense	剪髮診所	美妝保養
expense	剪髮書	美妝保養
expense	剪髮買	美妝保養
expense	剪髮日常	美妝保養
expense	貓砂中油	汽機車輛
expense	貓砂房租	居家水電
expense	貓砂netflix	數位訂閱
expense	貓砂剪髮	美妝保養
expense	貓砂機票	寵物毛孩
expense	貓砂喜酒	寵物毛孩
expense	貓砂保費	寵物毛孩
expense	貓砂飯	寵物毛孩
expense	貓砂捷運	寵物毛孩
expense	貓砂遊戲	寵物毛孩
expense	貓砂診所	寵物毛孩
expense	貓砂書	寵物毛孩
expense	貓砂買	寵物毛孩
expense	貓砂日常	寵物毛孩
expense	機票中油	汽機車輛
expense	機票房租	居家水電
expense	機票netflix	數位訂閱
expense	機票剪髮	美妝保養
expense	機票貓砂	寵物毛孩
expense	機票喜酒	旅行度假
expense	機票保費	旅行度假
expense	機票飯	旅行度假
expense	機票捷運	旅行度假
expense	機票遊戲	旅行度假
expense	機票診所	旅行度假
expense	機票書	旅行度假
expense	機票買	旅行度假
expense	機票日常	旅行度假
expense	喜酒中油	汽機車輛
expense	喜酒房租	居家水電
expense	喜酒netflix	數位訂閱
expense	喜酒剪髮	美妝保養
expense	喜酒貓砂	寵物毛孩
expense	喜酒機票	旅行度假
expense	喜酒保費	社交人情
expense	喜酒飯	社交人情
expense	喜酒捷運	社交人情
expense	喜酒遊戲	社交人情
expense	喜酒診所	社交人情
expense	喜酒書	社交人情
expense	喜酒買	社交人情
expense	喜酒日常	社交人情
expense	保費中油	汽機車輛
expense	保費房租	居家水電
expense	保費netflix	數位訂閱
expense	保費剪髮	美妝保養
expense	保費貓砂	寵物毛孩
expense	保費機票	旅行度假
expense	保費喜酒	社交人情
expense	保費飯	保險稅費
expense	保費捷運	保險稅費
expense	保費遊戲	保險稅費
expense	保費診所	保險稅費
expense	保費書	保險稅費
expense	保費買	保險稅費
expense	保費日常	保險稅費
expense	飯中油	汽機車輛
expense	飯房租	居家水電
expense	飯netflix	數位訂閱
expense	飯剪髮	美妝保養
expense	飯貓砂	寵物毛孩
expense	飯機票	旅行度假
expense	飯喜酒	社交人情
expense	飯保費	保險稅費
expense	飯捷運	餐飲
expense	飯遊戲	餐飲
expense	飯診所	餐飲
expense	飯書	餐飲
expense	飯買	餐飲
expense	飯日常	餐飲
expense	捷運中油	汽機車輛
expense	捷運房租	居家水電
expense	捷運netflix	數位訂閱
expense	捷運剪髮	美妝保養
expense	捷運貓砂	寵物毛孩
expense	捷運機票	旅行度假
expense	捷運喜酒	社交人情
expense	捷運保費	保險稅費
expense	捷運飯	餐飲
expense	捷運遊戲	交通
expense	捷運診所	交通
expense	捷運書	交通
expense	捷運買	交通
expense	捷運日常	交通
expense	遊戲中油	汽機車輛
expense	遊戲房租	居家水電
expense	遊戲netflix	數位訂閱
expense	遊戲剪髮	美妝保養
expense	遊戲貓砂	寵物毛孩
expense	遊戲機票	旅行度假
expense	遊戲喜酒	社交人情
expense	遊戲保費	保險稅費
expense	遊戲飯	餐飲
expense	遊戲捷運	交通
expense	遊戲診所	娛樂
expense	遊戲書	娛樂
expense	遊戲買	娛樂
expense	遊戲日常	娛樂
expense	診所中油	汽機車輛
expense	診所房租	居家水電
expense	診所netflix	數位訂閱
expense	診所剪髮	美妝保養
expense	診所貓砂	寵物毛孩
expense	診所機票	旅行度假
expense	診所喜酒	社交人情
expense	診所保費	保險稅費
expense	診所飯	餐飲
expense	診所捷運	交通
expense	診所遊戲	娛樂
expense	診所書	醫療
expense	診所買	醫療
expense	診所日常	醫療
expense	書中油	汽機車輛
expense	書房租	居家水電
expense	書netflix	數位訂閱
expense	書剪髮	美妝保養
expense	書貓砂	寵物毛孩
expense	書機票	旅行度假
expense	書喜酒	社交人情
expense	書保費	保險稅費
expense	書飯	餐飲
expense	書捷運	交通
expense	書遊戲	娛樂
expense	書診所	醫療
expense	書買	教育
expense	書日常	教育
expense	買中油	汽機車輛
expense	買房租	居家水電
expense	買netflix	數位訂閱
expense	買剪髮	美妝保養
expense	買貓砂	寵物毛孩
expense	買機票	旅行度假
expense	買喜酒	社交人情
expense	買保費	保險稅費
expense	買飯	餐飲
expense	買捷運	交通
expense	買遊戲	娛樂
expense	買診所	醫療
expense	買書	教育
expense	買日常	購物
expense	日常中油	汽機車輛
expense	日常房租	居家水電
expense	日常netflix	數位訂閱
expense	日常剪髮	美妝保養
expense	日常貓砂	寵物毛孩
expense	日常機票	旅行度假
expense	日常喜酒	社交人情
expense	日常保費	保險稅費
expense	日常飯	餐飲
expense	日常捷運	交通
expense	日常遊戲	娛樂
expense	日常診所	醫療
expense	日常書	教育
expense	日常買	購物
income	中油	
income	房租	
income	netflix	投資
income	剪髮	
income	貓砂	
income	機票	
income	喜酒	
income	保費	
income	飯	
income	捷運	
income	遊戲	
income	診所	
income	書	
income	買	
income	日常	
income	補貼	政府補貼
income	今天補貼費用	政府補貼
income	  補貼  	政府補貼
income	補助	政府補貼
income	今天補助費用	政府補貼
income	  補助  	政府補貼
income	津貼	政府補貼
income	今天津貼費用	政府補貼
income	  津貼  	政府補貼
income	退稅	政府補貼
income	今天退稅費用	政府補貼
income	  退稅  	政府補貼
income	租金補貼	政府補貼
income	今天租金補貼費用	政府補貼
income	  租金補貼  	政府補貼
income	育兒津貼	政府補貼
income	今天育兒津貼費用	政府補貼
income	  育兒津貼  	政府補貼
income	托育補助	政府補貼
income	今天托育補助費用	政府補貼
income	  托育補助  	政府補貼
income	節能補助	政府補貼
income	今天節能補助費用	政府補貼
income	  節能補助  	政府補貼
income	生育補助	政府補貼
income	今天生育補助費用	政府補貼
income	  生育補助  	政府補貼
income	紅包	禮金餽贈
income	今天紅包費用	禮金餽贈
income	  紅包  	禮金餽贈
income	壓歲錢	禮金餽贈
income	今天壓歲錢費用	禮金餽贈
income	  壓歲錢  	禮金餽贈
income	孝親費	禮金餽贈
income	今天孝親費費用	禮金餽贈
income	  孝親費  	禮金餽贈
income	親友給	禮金餽贈
income	今天親友給費用	禮金餽贈
income	  親友給  	禮金餽贈
income	長輩給	禮金餽贈
income	今天長輩給費用	禮金餽贈
income	  長輩給  	禮金餽贈
income	禮金	禮金餽贈
income	今天禮金費用	禮金餽贈
income	  禮金  	禮金餽贈
income	贈與	禮金餽贈
income	今天贈與費用	禮金餽贈
income	  贈與  	禮金餽贈
income	二手	二手出清
income	今天二手費用	二手出清
income	  二手  	二手出清
income	出清	二手出清
income	今天出清費用	二手出清
income	  出清  	二手出清
income	拍賣	二手出清
income	今天拍賣費用	二手出清
income	  拍賣  	二手出清
income	旋轉拍賣	二手出清
income	今天旋轉拍賣費用	二手出清
income	  旋轉拍賣  	二手出清
income	蝦皮賣家	二手出清
income	今天蝦皮賣家費用	二手出清
income	  蝦皮賣家  	二手出清
income	二手衣	二手出清
income	今天二手衣費用	二手出清
income	  二手衣  	二手出清
income	出清變現	二手出清
income	今天出清變現費用	二手出清
income	  出清變現  	二手出清
income	薪水	薪資
income	今天薪水費用	薪資
income	  薪水  	薪資
income	薪資	薪資
income	今天薪資費用	薪資
income	  薪資  	薪資
income	發薪	薪資
income	今天發薪費用	薪資
income	  發薪  	薪資
income	底薪	薪資
income	今天底薪費用	薪資
income	  底薪  	薪資
income	本薪	薪資
income	今天本薪費用	薪資
income	  本薪  	薪資
income	月薪	薪資
income	今天月薪費用	薪資
income	  月薪  	薪資
income	獎金	獎金
income	今天獎金費用	獎金
income	  獎金  	獎金
income	年終	獎金
income	今天年終費用	獎金
income	  年終  	獎金
income	三節	獎金
income	今天三節費用	獎金
income	  三節  	獎金
income	紅利	獎金
income	今天紅利費用	獎金
income	  紅利  	獎金
income	分紅	獎金
income	今天分紅費用	獎金
income	  分紅  	獎金
income	績效	獎金
income	今天績效費用	獎金
income	  績效  	獎金
income	股息	投資
income	今天股息費用	投資
income	  股息  	投資
income	利息	投資
income	今天利息費用	投資
income	  利息  	投資
income	股票	投資
income	今天股票費用	投資
income	  股票  	投資
income	基金	投資
income	今天基金費用	投資
income	  基金  	投資
income	獲利	投資
income	今天獲利費用	投資
income	  獲利  	投資
income	配息	投資
income	今天配息費用	投資
income	  配息  	投資
income	etf	投資
income	ETF	投資
income	今天etf費用	投資
income	  etf  	投資
income	美股	投資
income	今天美股費用	投資
income	  美股  	投資
income	證券	投資
income	今天證券費用	投資
income	  證券  	投資
income	兼職	兼職
income	今天兼職費用	兼職
income	  兼職  	兼職
income	副業	兼職
income	今天副業費用	兼職
income	  副業  	兼職
income	打工	兼職
income	今天打工費用	兼職
income	  打工  	兼職
income	接案	兼職
income	今天接案費用	兼職
income	  接案  	兼職
income	外快	兼職
income	今天外快費用	兼職
income	  外快  	兼職
income	鐘點	兼職
income	今天鐘點費用	兼職
income	  鐘點  	兼職
income	稿費	兼職
income	今天稿費費用	兼職
income	  稿費  	兼職
income	補貼紅包	政府補貼
income	補貼二手	政府補貼
income	補貼薪水	政府補貼
income	補貼獎金	政府補貼
income	補貼股息	政府補貼
income	補貼兼職	政府補貼
income	紅包補貼	政府補貼
income	紅包二手	禮金餽贈
income	紅包薪水	禮金餽贈
income	紅包獎金	禮金餽贈
income	紅包股息	禮金餽贈
income	紅包兼職	禮金餽贈
income	二手補貼	政府補貼
income	二手紅包	禮金餽贈
income	二手薪水	二手出清
income	二手獎金	二手出清
income	二手股息	二手出清
income	二手兼職	二手出清
income	薪水補貼	政府補貼
income	薪水紅包	禮金餽贈
income	薪水二手	二手出清
income	薪水獎金	薪資
income	薪水股息	薪資
income	薪水兼職	薪資
income	獎金補貼	政府補貼
income	獎金紅包	禮金餽贈
income	獎金二手	二手出清
income	獎金薪水	薪資
income	獎金股息	獎金
income	獎金兼職	獎金
income	股息補貼	政府補貼
income	股息紅包	禮金餽贈
income	股息二手	二手出清
income	股息薪水	薪資
income	股息獎金	獎金
income	股息兼職	投資
income	兼職補貼	政府補貼
income	兼職紅包	禮金餽贈
income	兼職二手	二手出清
income	兼職薪水	薪資
income	兼職獎金	獎金
income	兼職股息	投資
expense	補貼	
expense	二手	
expense	薪水	
expense	獎金	
expense	股息	
expense	兼職	
expense		
income		
expense	   	
income	   	
expense	zzz	
income	zzz	
expense	隨便寫寫	
income	隨便寫寫	
expense	123	
income	123	
expense	Netflix 月費	數位訂閱
income	Netflix 月費	投資
expense	早餐	餐飲
income	早餐	
income	下午茶	
expense	中油加油站	汽機車輛
income	中油加油站	
expense	全聯買菜	購物
income	全聯買菜	
expense	育兒津貼	
expense	薪水入帳	
income	薪水入帳	薪資
"""
}
